### ISSUE TITLE
[DOC] : Use the more common $GOPATH prefix in the project link

### ISSUE THREAD

**Issue by obeunda** [bruno-chavez/ancestorquotes#5]
README -> Installation documentation
Actual  : **GO_DIR**/src/github.com/bruno-chavez/ancetorquotes
Proposed : **$GOPATH**/src/github.com/<username>/ancetorquotes

**Comment by bruno-chavez** [comment]
nice catch! should have used the standard way of naming the go directory from the beginning, thank you. 

And for your suggestion about changing the sub directories, /src/github.com/bruno-chavez/ancetorquotes is the way go installs it by default and there is no way for me to change it, take a look at how Package Publishing is handled here: https://github.com/golang/go/wiki/PackagePublishing


As a side note, im also going to change the -u prefix on the installation part of the readme, since the only thing it does is update the package.

**Comment by bruno-chavez** [comment]
Just pushed a couple of changes to the README, let me know if you need anything else

**Comment by obeunda** [comment]
Great!
About changing the sub directories, i was considering the case where you get from the fork. But assuming not everyone will fork, keep it unchanged must be the right way to go.
